packages:
  - build-config-nodejs
  - claude-code-session-history
  - concurrency-limit
  - csv-tool
  - env-file-rewrite
  - fetch-sse-stream
  - file-manifest
  - generic-lexer
  - goob-static-web-server
  - goobernetes
  - parse-stdout-lines
  - port-assignment
  - prism-framework-api
  - prism-framework-tools
  - prism-framework-ui
  - react-elements
  - sqlite-migration
  - sqlite-wrapper
  - sqlite-wrapper/docs-site
  - streams
  - subprocess-wrapper
  - qc
  - userdata-db
  - userdata-db/docs-site

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
