packages:
  - claude-code-session-history
  - csv-tool
  - fetch-sse-stream
  - generic-lexer
  - parse-stdout-lines
  - prism-framework-api
  - prism-framework-tools
  - prism-framework-ui
  - sqlite-wrapper
  - streams
  - subprocess-wrapper

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild

overrides:
  '@facetlayer/prism-framework-api': link:prism-framework-api
