packages:
  - agent-hint-tool
  - build-config-nodejs
  - claude-code-headless
  - claude-code-session-history
  - claude-settings-tidier
  - claude-worktree-helper
  - concurrency-limit
  - csv-tool
  - doc-files-helper
  - env-file-rewrite
  - fetch-sse-stream
  - file-manifest
  - generic-lexer
  - goob-static-web-server
  - goobernetes
  - lsp-dev-tools
  - parse-stdout-lines
  - port-assignment
  - prism-framework-api
  - prism-framework-tools
  - prism-framework-ui
  - react-elements
  - sqlite-migration
  - sqlite-wrapper
  - sqlite-wrapper/docs-site
  - streams
  - subprocess-wrapper
  - qc
  - userdata-db
  - userdata-db/docs-site

onlyBuiltDependencies:
  - better-sqlite3
  - esbuild

overrides:
  '@facetlayer/build-config-nodejs': link:build-config-nodejs
  '@facetlayer/doc-files-helper': link:doc-files-helper
